package com.deepak.androidflickr.database;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.deepak.androidflickr.database.PhotoFlickr;

import com.deepak.androidflickr.database.PhotoFlickrDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig photoFlickrDaoConfig;

    private final PhotoFlickrDao photoFlickrDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        photoFlickrDaoConfig = daoConfigMap.get(PhotoFlickrDao.class).clone();
        photoFlickrDaoConfig.initIdentityScope(type);

        photoFlickrDao = new PhotoFlickrDao(photoFlickrDaoConfig, this);

        registerDao(PhotoFlickr.class, photoFlickrDao);
    }
    
    public void clear() {
        photoFlickrDaoConfig.getIdentityScope().clear();
    }

    public PhotoFlickrDao getPhotoFlickrDao() {
        return photoFlickrDao;
    }

}
